[package]
name = "licensor"
version = "1.0.0"
authors = ["Sean Clayton <sean@seanclayton.me>"]
edition = "2018"
license = "0BSD"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
license = "1.1.8"
