on: [push]

name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: linux-cargo-registry-%{{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            linux-cargo-registry-

      - uses: actions-rs/cargo@v1
        with:
          command: test
